---
title: 'Lab 01: Hello R'
author: "Jaxon Abercrombie"
date: "8/27/2021"
output:
  pdf_document: 
    toc: yes
    fig_height: 8
    highlight: tango
  html_document:
    toc: yes
    toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r include=FALSE}
# Load packages necessary for the lab
library(datasauRus)
library(tidyverse)
```

## Exercise 1

```{r}
?datasaurus_dozen

# In the datasaurus_dozen file, there are 1,846 rows and 3 columns.

# The variables included in the data frame are: dataset, x, and y.
```

## Exercise 2

```{r}
dino_data <- datasaurus_dozen %>%
  filter(dataset == "dino")

ggplot(data = dino_data, mapping = aes(x = x, y = y)) + 
  geom_point()

dino_data %>%
  summarize(r = cor(x,y))
```

## Exercise 3

```{r fig.height=6, fig.width=4}
star_data <- datasaurus_dozen %>%
  filter(dataset == "star")

ggplot(data = star_data, mapping = aes(x = x, y = y)) + 
  geom_point()

star_data %>%
  summarize(r = cor(x,y))
```

## Exercise 4

```{r}
circle_data <- datasaurus_dozen %>%
  filter(dataset == "circle")

ggplot(data = circle_data, mapping = aes(x = x, y = y)) + 
  geom_point()

circle_data %>%
  summarize(r = cor(x,y))
```

## Exercise 5

```{r}
ggplot(datasaurus_dozen, aes(x = x, y = y, color = dataset))+
  geom_point()+
  facet_wrap(~ dataset, ncol = 3) +
  theme(legend.position = "none")

datasaurus_dozen %>%
  group_by(dataset) %>%
  summarize(r = cor(x, y))
```
