---
title: "README"
author: "Jaxon Abercrombie"
date: "10/1/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### **Setup in R**

```{r}
#Packages
library(data.table)
library(dtplyr)
library(dplyr)

#Load in met data
met <- fread("met_all.gz")


#Stations read code from Lab 5 site
stations <- 
  fread("ftp://ftp.ncdc.noaa.gov/pub/data/noaa/isd-history.csv")
stations[, USAF := as.integer(USAF)]

stations[, USAF   := fifelse(USAF == 999999, NA_integer_, USAF)]
stations[, CTRY   := fifelse(CTRY == "", NA_character_, CTRY)]
stations[, STATE  := fifelse(STATE == "", NA_character_, STATE)]

stations <- unique(stations[, list(USAF, CTRY, STATE)])

stations <- stations[!is.na(USAF)]

stations[, n := 1:.N, by = .(USAF)]
stations <- stations[n == 1,][, n := NULL]

#Merging
met <- merge(
  x = met,
  y = stations,
  all.x = TRUE, all.y = FALSE,
  by.x = "USAFID", by.y = "USAF"
)
```

### **Question 1**

```{r median-temp}
# Averages
station_averages <- met[,.(
  temp = mean(temp, na.rm = TRUE),
  wind.sp = mean(wind.sp, na.rm = TRUE),
  atm.press = mean(atm.press, na.rm = TRUE),
  lon = lon,
  lat = lat,
  STATE = STATE.x
), by = USAFID]

# Medians
medians <- station_averages[,.(
  temp_50 = quantile(temp, probs = 0.5, na.rm = TRUE),
  wind.sp_50 = quantile(wind.sp, probs = 0.5, na.rm = TRUE),
  atm.press_50 = quantile(atm.press, probs = 0.5, na.rm = TRUE),
  lon = lon,
  lat = lat,
  STATE = STATE
)]

# Closest stations
station_averages[, temp_dist := abs(temp - medians$temp_50)]
median_temp_station <- station_averages[order(temp_dist)][1]
```

The median temperature station is `r median_temp_station$USAFID`

### **Question 2**

```{r}
station_averages <- merge(
  x = station_averages,
  y = stations,
  all.x = TRUE, all.y = FALSE,
  by.x = "USAFID", by.y = "USAF"
)

station_averages[, temp_50 := quantile(temp, probs = .5, na.rm = TRUE), by = STATE.x]
station_averages[, wind.sp_50 := quantile(wind.sp, probs = .5, na.rm = TRUE), by = STATE.x]
station_averages[, atm.press_50 := quantile(atm.press, probs = .5, na.rm = TRUE), by = STATE.x]

```

```{r}
station_averages[, eudist := sqrt(
  (temp - temp_50)^2 + (wind.sp - wind.sp_50)^2
)]
```

### **Question 3**

```{r}
#Compute medians of latitude and longitude
center <- met[, .(
  lon = quantile(lon, probs = 0.5, na.rm = TRUE),
  lat = quantile(lat, probs = 0.5, na.rm = TRUE)
), 
by = STATE.x]

#Compute distance
medians <- station_averages[, dist1 := sqrt(
  (lat - lat_50)^2 + (lon - lon_50)^2
)]

#Observations for closest to middle
closest <- station_averages[, .SD[which.min(dist1)], by = STATE.x]

#Combine Data
comboData <- rbind(closest,center, fill = TRUE)

#Leaflet
library(leaflet)

leaflet() %>% 
  addProviderTiles('CartoDB.Positron') %>% 
  addCircles(
    data = comboData,
    lat = ~lat, lng = ~lon, 
    opacity = 1, fillOpacity = 1, radius = 200, color = 2)
```

### **Question 4**

```{r}
met[, state_temp := mean(temp, na.rm = TRUE), by = STATE.x]
met[, state_wind := mean(wind.sp, na.rm = TRUE), by = STATE.x]
met[, state_press := mean(atm.press, na.rm = TRUE), by = STATE.x]
met[, temp_cat := fifelse(
  state_temp < 20, "low-temp",
  fifelse(state_temp < 25, "mid-temp", "high-temp"))
  ]

table(met$temp_cat, useNA = "always")

tab <- met[, .(
  nEntries = .N,
  nStations = length(unique(USAFID)),
  nStates = length(unique(STATE.x)),
  aveTemp = mean(state_temp),
  aveWind = mean(state_wind),
  avePress = mean(state_press)
), by = temp_cat]

knitr::kable(tab)
```

xx